package picodiploma.kiky.masakanbatak;

import java.util.ArrayList;

public class FoodData {
    public static String[][] data = new String[][]{
            {"Arsik", "https://www.konfrontasi.com/sites/default/files/styles/article_big/public/article/2018/08/7.jpg?itok=m4ddxKyP",
                    "Arsik adalah salah satu masakan khas Batak yang paling banyak digunakan pada saat acara adat dengan bahan dasar ikan seperti ikan mas, nila dan ikan mujahir.",
                    "1.\t\t1 Kg ikan mas\n2.\t\tSegenggam andaliman\n3.\t\t15 buah cabai merah keriting\n3.\t\t10 buah cabai rawit merah\n4.\t\t8 butir bawang merah\n5.\t\t5 siung bawang putih\n6.\t\t1 ruas jahe (3 Cm)\n7.\t\t1 ruas lengkuas (3 Cm)\n8.\t\t2 ruas kunyit (6 Cm)\n9.\t\t4 butir kemiri\n10.\t\t2 batang serai\n11.\t\t2 buah kincung (kecombrang)\n12.\t\t10 buah asam cekala (buah kecombrang)\n13.\t\t150 Gr kacang panjang\n14.\t\t100 Gr bawang batak\n15.\t\t1 liter air\n16.\t\tsecukupnya garam\n",
                    "1.\tCuci bersih ikan mas, potong sesuai selera\n2.\tHaluskan : Cabai merah keriting, cabai rawit, bawang merah, bawang putih, kunyit, jahe, lengkuas, andaliman, dan kemiri dengan sedikit air.\n3.\tKeprek serai dan asam cekala\n4.\tPotong-potong kacang panjang sekitar 5 Cm\n5.\tBersihkan bawang batak dari daun-daunan yg kering, biarkan panjang-panjang\n6.\tSusun di wajan mulai serai, asam cekala, bawang batak, kecombrang dan kacang panjang\n7.\tLalu taruh diatasnya ikan mas yg sudah dipotong-potong dan bumbu halus\n8.\tTambahkan air hingga ikan terendam. Tambahkan garam sesuai selera.\n9.\tMasak hingga airnya hampir kering\n10.\tSetelah airnya hampir kering, angkat dan sajikan. Arsik semakin enak bila dipanasi keesokan harinya. Bumbunya semakin meresap.\n"},
            {"Naniura", "https://static.inilah.com/data/berita/foto/2318853.jpg",
                    "Naniura merupakan makanan berbahan dasar ikan mas, ikan nila atau pun ikan mujahir yang tidak dimasak, digoreng ataupun direbus.",
                    "1.\t\t1 kg Ikan mas segar\n2.\t\t3 bh Asam jungga atau 10 bh jeruk nipis (ambil sarinya)\n3.\t\t1 sdm Andaliman \n4.\t\t100 gr Kemiri, sangrai\n5.\t\t5 cm Lengkuas, parut, ambil airnya\n6.\t\t10 cm Kunyit\n7.\t\t2 bunga Rias (kecombrang/honje), kukus sampai empuk\n8.\t\t10 siung Bawang merah\n9.\t\t6 siung Bawang putih\n10.\t\t100 gr Cabe merah keriting\n11.\t\tsecukupnya Garam\n12.\t\tsecukupnya Minyak goreng\n",
                    "1.\tBersihkan ikan mas dari sisiknya dan potong ikan mas untuk mengambil dagingnya.\n2.\tGoreng kunyit, bawang merah dan bawang putih hinga matang. Sisihkan.\n3.\tBlender seluruh bumbu (andaliman, kemiri, bahan digoreng, cabe merah) dengan sedikit air hingga halus.\n4.\tBila sudah halus, campur dengan air jeruk nipis dan sari lengkuas. Tambahkan garam secukupnya.\n5.\tBalurkan seluruh ikan dengan bumbu. Bila masih tersisa lebih bagus lagi jika ikan sampai terendam oleh bumbu.\n6.\tDiamkan dan tutup selama minimal 5 jam, untuk mematangkan daging ikan dan bumbu meresap.\n7.\tSajikan bersama nasi panas.\n"},
            {"Natinombur", "https://tourtoba.com/wp-content/uploads/2018/08/natinombur-2.jpg",
                    "Natinombur adalah ikan yang disiram dengan bumbu dan berbahan dasar ikan yang dibakar, biasanya menggunakan ikan nila atau pun mujahir",
                    "1.\t\t1/2 kg ikan (lele/mujahir/ikan mas/nila)\n2.\t\t1 gram Andaliman\n3.\t\t4 siung bawang merah\n4.\t\t3 siung bawang putih\n5.\t\t8 biji cabe rawit (saya pakai rawit merah)\n6.\t\t5 buah jeruk nipis\n7.\t\t7 butir kemiri\n8.\t\t2 buah tomat\n9.\t\t1 ruas jahe (se ibu jari)\n10.\t\t1 gram bawang rumput(kucai)\n11.\t\tsecukupnya Garam\n",
                    "1.\tBersihkan ikan kemudian kerat-kerat dagingnya. Lumuri garam dan beri perasan 2 buah jeruk nipis. Diamnkan 15 menit. Kemudian bakar/panggang hingga matang.\n2.\tSetelah ikan nya matang, siwir-siwir dan buang tulang nya (tapi jangan kecil-kecil). 1 ekor ikan bisa jadi 10 potong atau 8 potong. Kalo bagian kepala biarkan utuh saja.\n3.\tRebus bawang rumput (kucai) (yang sudah dibersihkan dan dipotong-potong terlebih dahulu) selama 5 menit juga,,beri minyak 1 sdm ke air rebusan.tiriskan\n4.\tRebus bawang merah, bawang putih, cabe rawit selama 5 menit.tiriskan\n5.\tGoreng kemiri hingga warna keemasan, kemudian tiriskan. Goreng juga tomat sampai kulitnya agak terkelupas.\n6.\tGiling/tumbuk halus andaliman, jahe, cabe, bawang merah, bawang putih, dan kemiri, beri 2 sdt garam. Masukkan dalam wadah\n7.\tTumbuk bawang rumput (kucai) dan tomat sebentar saja, jangan sampai hancur. Campurkan dalam wadah bumbu halus tadi.\n8.\tMasukkan air panas ke dalam wadah sampai kelihatan mengental sambil diaduk-aduk..cek rasa dan masukkan ikan yang disiwir-siwir tadi.\n9.\tMasukkan perasan jeruk nipis 3 buah. Cek kembali rasa,dan tingkat kepedasan..bila masih kurang, boleh ditambah sesuai selera\n"},
            {"Manuk Napinadar", "http://1.bp.blogspot.com/-YwqcvRR_Lm8/Vt1ZERdAo-I/AAAAAAAABAk/pTM0wySW6aM/s1600/2016-07-3--17-33-42.png",
                    "Manuk Napinadar merupakan masakan yang berbahan dasar ayam yang dibumbui dan dicampurkan dengan darah segar ayam itu sendiri dengan proses kematangan yang tepat.",
                    "1.\t\t1 kg Ayam kampung\n2.\t\tDarah dari 1 ekor ayam, campur dengan:\n3.\t\t1 sdt Garam\n4.\t\t2 buah jeruk nipis\n5.\t\tBumbu halus yang disangrai:\n6.\t\t2 buah Serai dipotong kecil\n7.\t\t5 cm Lengkuas dipotong kecil\n8.\t\t7 cm jahe dipotong kecil\n9.\t\t5 cm kunyit\n10.\t\t5 siung bawang putih\n11.\t\t10 siung bawang merah\n12.\t\t10 biji kemiri\n13.\t\tBumbu halus yang tidak disangrai\n14.\t\t15 buah cabe rawit atau secukupnya\n15.\t\tsecukupnya andaliman\n16.\t\tsesuai selera garam\n",
                    "1.\tAyam disembelih, dibului, dipotong-potong dan dibakar tanpa bumbu hingga matang.\n2.\tSangrai atau bakar semua bumbu yang disangrai Kemudian giling semua bumbu yang disangrai atau blender semuanya dalam satu wadah ditambah dengan bumbu halus yang tidak disangrai.\n3.\tTumis semua bumbu dan campurkan dengan darah ayam yang masih mencair.\n4.\tAduk merata kemudian masukkan potongan ayam panggang sampai terendam dengan bumbu. Kemudian siap disajikan.\n"},
            {"Mi gomak", "https://backpackerjakarta.com/wp-content/uploads/2016/09/Mie-Gomak.jpg",
                    "Mi Gomak adalah Spaghetti khas Batak yang menggetarkan lidah karena menggunakan Andaliman sebagai bumbu yang memberika rasa unik.",
                    "1.\t\t1/2 kg mie lidi\n2.\t\tSantan (bisa menggunakan 1buah santan kara)\n3.\t\t1 buah telur (optional)\n4.\t\tDaun bawang\n5.\t\tGaram\n6.\t\tBahan untuk ditumis :\n7.\t\t2 buah sayur labu diiris sesuai selera. Kalau aku diiris tipis memanjang. (Kalau tidak ada bisa diganti dengan 1 ikat sayur sawi atau kol)\n8.\t\t3 siung bawang merah\n9.\t\t1 siung bawang putih\n10.\t\tBahan yang dihaluskan :\n11.\t\t15 buah cabe merah/rawit (sesuai selera suka pedas atau tidak)\n12.\t\t5 siung bawang merah\n13.\t\t1 siung bawang putih\n14.\t\t1 ruas ibu jari kunyit\n15.\t\t1 ruas ibu jari jahe\n",
                    "1.\tAir kurang lebih 1 liter direbus sampe mendidih. Setelah mendidih, masukkan mie lidi. Sesekali aduk sampe mie nya matang. Tapi jangan terlalu matamg karna nanti akan ditumis, takutnya mie nya terlalu lembek. Setelah mie nya matang, angkat dan tiriskan mie. Cuci mie dengan air bersih. Air hasil rebusan jangan dibuang.\n2.\tTumis bawang putih dan bawang merah sampe harum, kemudian masukkan sayur sampe layu dan matang, masukkan juga 1/2sdm garam. Masukkan mie dan aduk sampe semua tercampur rata. Setelah masak, sisihkan ke dalam wadah untuk mie.\n3.\tUntuk kuah : \n Tumis bahan yang dihaluskan dengan minyak secukupnya. Aduk sampe matang, kemudian masukkan air hasil rebusan mie dan 1 gelas air. Aduk2 sampe mendidih, kemudian masukkan santan, daun bawang yang telah diiris2 dan telur. Masukkan juga garam secukupnya. Aduk2 supaya santan tidak pecah. Koreksi rasa. Setelah mendidih, masukkan ke wadah.\n4.\tMi gomak siap disajikan\n"},
            {"Kue Ombus-Ombus", "https://www.tobatabo.com/pictures/full/full_0d7d34dac217b9fa6ff81d5716d9e6a09e8bbc25.jpg",
                    "Kue Ombusombus adalah makanan atau jajanan khas Batak yang berasal dari Siborongborong, Tapanuli Utara yang terbuat dari tepung beras yang diberi gula di tengahnya dan dibungkus dengan daun pisang.",
                    "1.\t\t800 gr tepung beras (me 400 gr)\n2.\t\t2 buah kelapa parut, ambil bagian putihnya (me 1 buah)\n3.\t\t4 sdt garam (me : 2 sdt)\n4.\t\t250 gr gula merah, sisir\n5.\t\tsecukupnya daun pisang\n",
                    "1.\tCampur semua bahan, aduk sampai rata\n2.\tAmbil 1 lembar daun pisang dan bentuk kerucut, lalu masukkan 2-3 sendok makan adonan, tambahkan gula merah sisir lalu tutup lagi dg adonan. rapikan daun hingga tetutup rapat\n3.\tKukus selama 30 menit. angkat dan sajikan selagi hangat.\n"},
            {"Lomang", "https://cdn.idntimes.com/content-images/post/20180504/resep-kolo-khas-ntt-5ff39cfd6233af4c4aebb4d64e52cbd5-850x350-0f36a9437bbf26e5c3697c40f6ecd26e_600x400.jpg",
                    "lomang merupakan makanan pengganti ketupat di hari raya lebaran yang terbuat dari beras pulut dan santan yang dimasak dalam bambu panjang, setelah sebelumnya dibungkus daun pisang.",
                    "1.\t\t2 liter beras ketan putih, rendam selama 1 jam dalam air bersih lalu tiriskan\n2.\t\t2 liter santan kental\n3.\t\t2 siung bawang putih, tumabuk halus\n4.\t\tSatu setengah sendok teh garam\n5.\t\tBatang bambu besar secukupnya, potong mengikuti ruas dan biarkan satu ruasnya tertutup\n6.\t\tDaun pisang muda secukupnya\n",
                    "1.\tSiapkan batang bambu yang telah dipotong. Lapisi bagian dalamnya dengan 1 lembar daun pisang dan biarkan lebih sedikit dia atasnya.\n2.\tCampur santan, garam dan bawang putih. Aduk rata.\n3.\tMasukkan beras ketan kira-kira seperempat dari tinggi bambu.\n4.\tLakukan hal yang sama hingga beras ketan habis.\n5.\tSiapkan bara api. Buat dua tiang di sisi kiri dan kanannya, beri satu batang bambu melintang yang menghubungkannya. Letakkan bambu yang telah diisi dengan posisi sedikit miring bertumpu di kayu melintang tersebut.\n6.\tMasak hingga matang dan biasanya batang bambu akan retak.\n"},
            {"Dali Ni Horbo / Keju Batak", "https://3.bp.blogspot.com/-gU1buVt76xU/WgwP5fS4wOI/AAAAAAAAH9s/60ex7EQ6t6Qk0BdueH0eoKHbf1FvBoicACLcBGAs/s640/001.jpg",
                    "Dali Ni Horbo adalah susu kerbau yang diolah secara tradisional dan cukup banyak ditemukan di daerah Batak. Sama dengan susu lainnya mengandung lemak, karbohidrat dan protein perbedaannya bahwa susu ini diolah tanpa mengandung bahan kimia.",
                    "1.\t\t1 liter susu kerbau \n 2.\t\tAir perasan 1 lembar daun pepaya hijau yang segar(Untuk mengurangi bau amisnya)\n3.\t\tPerasan air nenas segar dari separuh nenas (Untuk membantu proses pengentalan)\n",
                    "1.\tMasukkan susu kerbau/sapi kedalam panci yang steril, dan rebus hingga mendidih (kurang lebih 10 menit).\n2.\tKurangi besarnya api, dan masukkan air nenas secara perlahan untuk membantu pengentalan.\n3.\tTambahkan air perasan daun pepaya secukupnya, dan didihkan beberapa menit lagi.\n4.\tSetelah itu, angkat dari api, lalu tuangkan ketempat penghidangan terakhir dan biarkan hingga dingin.\n5.\tJika anda memiliki pendingin, silahkan masukkan kedalam pendingin, supaya hasilnya semakin segar.\n"},
            {"Daun Ubi Tumbuk", "https://selerasa.com/wp-content/uploads/2015/10/images_Aneka_Sayur_Syaur_Daun_Singkong_15.jpg",
                    "Daun ubi tumbuk merupakan sayuran yang ditumbuk dan dicampur dengan berbagai macam bumbu masakan yang konon daun ubi menjadi sayur yang paling mudah untuk didapatkan karena hanya meletakkan kayunya saja akan muncul tunas-tunas daun ubi.",
                    "1.\t\t1 ikat Daun Singkong (pilih yang muda)\n2.\t\t1 genggam Rimbang/Tekokak\n3.\t\t1 bh Kecombrang/Kincung (optional)\n4.\t\tAmbil dari 1 butir kelapa :\n5.\t\t1 gelas Santan Kental\n6.\t\t2 gelas Santan Encer\n7.\t\t1 btg Sereh\n8.\t\t3 lbr Daun Salam\n9.\t\t1 ruas Lengkuas (geprek)\n10.\t\tBumbu Halus:\n11.\t\t4 bh Bawang Merah\n12.\t\t1 siung Bawang Putih\n13.\t\t3 bh Cabe Merah\n14.\t\t1 cm Jahe\n15.\t\t2 cm Kunyit\n16.\t\tSecukupnya Garam\n17.\t\tSecukupnya Gula\n",
                    "1.\tTumbuk daun ubi bersamaan: daun singkong, kecombrang dan rimbang/tekokak (sisihkan).\n2.\tDidihkan santan encer dalam panci. Setelah itu masukkan bumbu halus, salam, sereh, lengkuas dan tumbukan daun singkong. Masak beberapa saat.\n3.\tMasukkan santan kental, garam, gula. Masak hingga matang. Cek rasa. Angkat.\n"},
            {"Daun Ubi Jantung Pisang", "http://3.bp.blogspot.com/-RP3ceXcl-RU/T9YA2rkGZKI/AAAAAAAABZE/zyXd2PP0v2Q/s1600/DSC_0597.jpg",
                    "Daun ubi jantung pisang merupakan masakan yang hampir mirip dengan daun ubi tumbuk, daun ubi jantung pisang ditambah dengan potongan jantung pisang yang diiris kecil-kecil, dan kelapa parut.",
                    "1.\t\t1 buah jantung pisang (bakar diatas arang biar tidak kaku)\n2.\t\t1 genggam daun singkong rebus (potong2)\n3.\t\tBumbu:\n4.\t\t8 bawang merah\n5.\t\t3 bawang putih\n6.\t\t6 cabe rawit (sesuai selera, lebih enak kalo pedas)\n7.\t\t1 buah santan kara\n8.\t\t1 ruas jahe\n9.\t\t1 ruas lengkuas\n10.\t\t3 lbr daun salam\n11.\t\t3 sdm rese (udang rebon)\n12.\t\t1 potong tempe semanget (bisa diganti terasi goreng)\n13.\t\tSecukupnya garam, gula merah, kaldu jamur\n14.\t\tAir menyesuaikan selera, kuahnya mau kental atau encer\n",
                    "1.\tBersihkan jantung pisang hingga ke bagian yang putih, lalu potong2, bagian tengah yang keras jangan lupa dibuang.\n 2\tBumbu bisa dirajang ato diuleg, (me dirajang), lalu tumis.\n3.\tSetelah itu masukkan jantung dan daun singkong, aduk2 tambah air sedikit.\n4.\tTambahkan air dan santannya separo dulu ya, tes rasa. Masak sampai matang.\n5.\tKalo sudah matang tambahkan sisa santannya, aduk2 tunggu sebentar sampai mendidih kembali kuahnya, lalu angkat.\n6.\tCampuran daun singkong bisa diganti tempe atau tahu kulit kecil2.\n"},
    };

    public static ArrayList<Food> getListData(){
        Food food = null;
        ArrayList<Food> list = new ArrayList<>();
        for (int i = 0; i < data.length;i++){
            food = new Food();
            food.setName(data[i][0]);
            food.setPhoto(data[i][1]);
            food.setArti(data[i][2]);
            food.setBahan(data[i][3]);
            food.setLangkah(data[i][4]);

            list.add(food);
        }

        return list;
    }
}
